blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

codestar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls"), name="blog-urls"),
    path('summernote/', include('django_summernote.urls')),
    path("accounts/", include("allauth.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


# Create your models here.


STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from .models import Post


class PostList(generic.ListView):
    model = Post
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "index.html"
    paginate_by = 6


class PostDetail(View):

    def get(self, request, slug, *args, **kwargs):
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "liked": liked
            },
        )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>CodeStar Blog</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><span class="brand">c<span class="red-o">o</span>de<span
                        class="thin">|star</span></span></span></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}

                </ul>
                <span class="navbar-text text-muted">
                    adventures of a software developer
                </span>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <main class="flex-shrink-0 main-bg">

        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 dark-bg">
        <p class="m-0 text-center text-white">Made by Code Instituters</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 2500);
    </script>
</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                                {% else %}
                                <img class="card-img-top" src=" {{ post.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug  %}" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr />
                            <p class="card-text text-muted h6">{{ post.created_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}

            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{%endblock%}

templates/mfa/authenticate.html
{% extends "mfa/base_entrance.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_authenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Sign In" %}
            {% endelement %}
            {% url "account_login" as login_url %}
            {% element button href=login_url tags="link,secondary,mfa,cancel" %}
                {% trans "Cancel" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/base_entrance.html
{% extends "allauth/layouts/entrance.html" %}

templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}

templates/mfa/index.html
{% extends "mfa/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="mfa,index" %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% if "totp" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Authenticator App" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.totp %}
                    {% element p %}
                        {% translate "Authentication using an authenticator app is active." %}
                    {% endelement %}
                {% else %}
                    {% element p %}
                        {% translate "An authenticator app is not active." %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% url 'mfa_deactivate_totp' as deactivate_url %}
                {% url 'mfa_activate_totp' as activate_url %}
                {% if authenticators.totp %}
                    {% element button href=deactivate_url tags="danger,delete,panel" %}
                        {% translate "Deactivate" %}
                    {% endelement %}
                {% else %}
                    {% element button href=activate_url tags="panel" %}
                        {% translate "Activate" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "recovery_codes" in MFA_SUPPORTED_TYPES %}
        {% with total_count=authenticators.recovery_codes.generate_codes|length unused_count=authenticators.recovery_codes.get_unused_codes|length %}
            {% element panel %}
                {% slot title %}
                    {% translate "Recovery Codes" %}
                {% endslot %}
                {% slot body %}
                    {% if authenticators.recovery_codes %}
                        {% element p %}
                            {% blocktranslate count unused_count=unused_count %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
                        {% endelement %}
                    {% else %}
                        {% element p %}
                            {% translate "No recovery codes set up." %}
                        {% endelement %}
                    {% endif %}
                {% endslot %}
                {% if is_mfa_enabled %}
                    {% if authenticators.recovery_codes %}
                        {% if unused_count > 0 %}
                            {% slot actions %}
                                {% url 'mfa_view_recovery_codes' as view_url %}
                                {% element button href=view_url tags="panel" %}
                                    {% translate "View" %}
                                {% endelement %}
                            {% endslot %}
                            {% slot actions %}
                                {% url 'mfa_download_recovery_codes' as download_url %}
                                {% element button href=download_url tags="secondary,panel" %}
                                    {% translate "Download" %}
                                {% endelement %}
                            {% endslot %}
                        {% endif %}
                    {% endif %}
                    {% slot actions %}
                        {% url 'mfa_generate_recovery_codes' as generate_url %}
                        {% element button href=generate_url tags="secondary,panel" %}
                            {% translate "Generate" %}
                        {% endelement %}
                    {% endslot %}
                {% endif %}
            {% endelement %}
        {% endwith %}
    {% endif %}
{% endblock content %}

templates/mfa/reauthenticate.html
{% extends "account/base_reauthenticate.html" %}
{% load i18n %}
{% load allauth %}
{% block reauthenticate_content %}
    {% element p %}
        {% blocktranslate %}Enter an authenticator code:{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_reauthenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
            {{ redirect_field }}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Confirm" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock %}

templates/mfa/recovery_codes/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account.{% endblocktranslate %}
        {% if unused_code_count %}
            {% blocktranslate %}This action will invalidate your existing codes.{% endblocktranslate %}
        {% endif %}
        {% blocktranslate %}Are you sure?{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_generate_recovery_codes' as action_url %}
    {% element form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endslot %}
        {% slot actions %}
            {% setvar tags %}
                {% if unused_code_count %}
                    danger
                {% else %}
                {% endif %}
            {% endsetvar %}
            {% element button type="submit" tags=tags %}
                {% trans "Generate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    {% endelement %}
    {% element field id="recovery_codes" type="textarea" disabled=True rows=unused_codes|length readonly=True %}
        {% slot label %}
            {% translate "Unused codes" %}
        {% endslot %}
        {% comment %} djlint:off {% endcomment %}
    {% slot value %}{% for code in unused_codes %}{% if forloop.counter0 %}
{% endif %}{{ code }}{% endfor %}{% endslot %}
{% comment %} djlint:on {% endcomment %}
{% endelement %}
{% if unused_codes %}
{% url 'mfa_download_recovery_codes' as download_url %}
{% element button href=download_url %}
{% translate "Download codes" %}
{% endelement %}
{% endif %}
{% url 'mfa_generate_recovery_codes' as generate_url %}
{% element button href=generate_url %}
{% translate "Generate new codes" %}
{% endelement %}
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load allauth i18n %}
{% block head_title %}
    {% translate "Activate Authenticator App" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% translate "Activate Authenticator App" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}To protect your account with two-factor authentication, scan the QR code below with your authenticator app. Then, input the verification code generated by the app below.{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_activate_totp' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% element img src=totp_svg_data_uri alt=form.secret tags="mfa,totp,qr" %}
            {% endelement %}
            {% csrf_token %}
            {% element field id="authenticator_secret" type="text" value=form.secret disabled=True %}
                {% slot label %}
                    {% translate "Authenticator secret" %}
                {% endslot %}
                {% slot help_text %}
                    {% translate "You can store this secret and use it to reinstall your authenticator app at a later time." %}
                {% endslot %}
            {% endelement %}
            {% element fields form=form %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" %}
                {% trans "Activate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/totp/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Deactivate Authenticator App" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Deactivate Authenticator App" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_deactivate_totp' as action_url %}
    {% element form form=form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form %}
                {{ form.as_p }}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button tags="danger,delete" type="submit" %}
                {% trans "Deactivate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Post author goes before the | the post's created date goes after -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                <!-- The featured image URL goes in the src attribute -->
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src=" {{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <!-- The post content goes inside the card-text. -->
                <!-- Use the | safe filter inside the template tags -->
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">

                    <div class="col-1">
                        <!-- The number of likes goes before the closing strong tag -->
                        <strong class="text-secondary"><i class="far fa-heart"></i> {{ post.number_of_likes }} </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                <!-- We want a for loop inside the empty control tags to iterate through each comment in comments -->
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        <!-- The commenter's name goes here. Check the model if you're not sure what that is -->
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            <!-- The comment's created date goes here -->
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    <!-- The body of the comment goes before the | -->
                    {{ comment.body | linebreaks }}
                </div>
                <!-- Our for loop ends here -->
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                <!-- For later -->
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/usersessions/base_manage.html
{% extends "allauth/layouts/manage.html" %}

templates/usersessions/usersession_list.html
{% extends "usersessions/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% load humanize %}
{% block head_title %}
    {% trans "Sessions" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="usersessions,list" %}
        {% trans "Sessions" %}
    {% endelement %}
    {% if session_count > 1 %}
        {% url 'usersessions_list' as action_url %}
    {% else %}
        {% url 'account_logout' as action_url %}
    {% endif %}
    {% element form action=action_url method="post" tags="sessions" no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {% element table tags="sessions" %}
                <thead>
                    <tr>
                        <th>{% translate "Started At" %}</th>
                        <th>{% translate "IP Address" %}</th>
                        <th>{% translate "Browser" %}</th>
                        {% if show_last_seen_at %}
                            <th>{% translate "Last seen at" %}</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for session in sessions %}
                        <tr>
                            <td>
                                <span title="{{ session.created_at }}">{{ session.created_at|naturaltime }}</span>
                            </td>
                            <td>{{ session.ip }}</td>
                            <td>{{ session.user_agent }}</td>
                            {% if show_last_seen_at %}
                                <td>
                                    <span title="{{ session.last_seen_at }}">{{ session.last_seen_at|naturaltime }}</span>
                                </td>
                            {% endif %}
                            <td>
                                {% if session.is_current %}
                                    {% element badge tags="session,current" %}
                                        {% translate "Current" %}
                                    {% endelement %}
                                {% else %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% if session_count > 1 %}
                {% element button type="submit" %}
                    {% translate "Sign Out Other Sessions" %}
                {% endelement %}
            {% else %}
                {% element button type="submit" %}
                    {% translate "Sign Out" %}
                {% endelement %}
            {% endif %}
        {% endslot %}
    {% endelement %}
{% endblock content %}